#######################################
#
# docker-compose-https.yml
#
# Add-on compose file for https
#
# Copyright (c) 2020 Philippe Vanhaesendonck
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# SPDX-License-Identifier: UPL-1.0
#
# Add https port for NGINX and define an additional service (proxy-letsencrypt)
# which handles the Let's Encrypt certificates for the exposed services
# (Grafana dashboard and Node-RED)
#
#######################################

version: '3.5'
services:
  node-red:
    labels:
      # For Web, only redirection
      - traefik.http.routers.ttn-node-red.middlewares=hsts@file
      # HTTPS
      - traefik.http.routers.ttn-node-red-https.entrypoints=${TRAEFIK_EP_WEBSECURE:-websecure}
      - traefik.http.routers.ttn-node-red-https.rule=Host(`${TTN_NODE_RED_HOST:?Hostname for Node-RED is mandatory}`)
      - traefik.http.routers.ttn-node-red-https.service=ttn-node-red
      - traefik.http.routers.ttn-node-red-https.middlewares=ttn-node-red-auth, hsts@file
      - traefik.http.routers.ttn-node-red-https.tls.certresolver=le

  grafana:
    labels:
      # For Web, only redirection
      - traefik.http.routers.ttn-grafana.middlewares=hsts@file
      # HTTPS
      - traefik.http.routers.ttn-grafana-https.entrypoints=${TRAEFIK_EP_WEBSECURE:-websecure}
      - traefik.http.routers.ttn-grafana-https.rule=Host(`${TTN_GRAFANA_HOST:?Hostname for Grafana is mandatory}`)
      - traefik.http.routers.ttn-grafana-https.service=ttn-grafana
      - traefik.http.routers.ttn-grafana-https.middlewares=hsts@file
      - traefik.http.routers.ttn-grafana-https.tls.certresolver=le

