#######################################
#
# docker-compose-net.yml
#
# Add-on compose file for external
#
# Copyright (c) 2020 Philippe Vanhaesendonck
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# SPDX-License-Identifier: UPL-1.0
#
# Define the default network as external.
# Other services can then make use of the proxy.
#
# Network needs to be created manually, e.g.:
#   docker network create proxy-net
#   docker-compose -f docker-compose.yml \
#                  -f docker-compose-https.yml \
#                  -f docker-compose-net.yml \
#                  up
#
#######################################

version: '3.5'
networks:
  default:
    external:
      name: ${PROXY_NET:-proxy-net}
