#######################################
#
# docker-compose-htpasswd.yml
#
# Add-on compose file to provide htpasswd
#
# Copyright (c) 2019 Philippe Vanhaesendonck
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
# SPDX-License-Identifier: UPL-1.0
#
# Simple service to provide the htpasswd tool.
# Usage: docker-compose -f docker-compose.yml -f docker-compose-htpasswd.yml \
#   run --rm htpasswd ./bin/htpasswd -bc data/proxy/htpasswd/<hostname> \
#   <user> <password>
#
#######################################

version: '3.5'
services:
  htpasswd:
    image: httpd
    restart: "no"
    # Does nothing if started
    command: sleep 10
    volumes:
      - proxy_passwd:/htpasswd
